import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `{{cubit_name.snakeCase()}}_state.dart` with the code generated by Freezed
part '{{cubit_name.snakeCase()}}_state.freezed.dart';

@freezed
class {{cubit_name.pascalCase()}}State with _${{cubit_name.pascalCase()}}State {
  const factory {{cubit_name.pascalCase()}}State({
  required bool isLoading,
  Object? data,
  String? error,
  }) = _{{cubit_name.pascalCase()}}State;
}

