import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `{{cubit_name.snakeCase()}}_state.dart` with the code generated by Freezed
part '{{bloc_name.snakeCase()}}_state.freezed.dart';

@freezed
class {{bloc_name.pascalCase()}}State with _${{bloc_name.pascalCase()}}State {
  const factory {{bloc_name.pascalCase()}}State({
  required bool isLoading,
  Object? data,
  String? error,
  }) = _{{bloc_name.pascalCase()}}State;
}

