import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `{{cubit_name.snakeCase()}}_event.dart` with the code generated by Freezed
part '{{bloc_name.snakeCase()}}_event.freezed.dart';

@freezed
class {{bloc_name.pascalCase()}}Event with _${{bloc_name.pascalCase()}}Event {
  const factory {{bloc_name.pascalCase()}}Event.fetch() = {{bloc_name.pascalCase()}}Fetch;
}
