import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `_event.dart` with the code generated by Freezed
part 'weather_event.freezed.dart';

@freezed
class WeatherEvent with _$WeatherEvent {
  const factory WeatherEvent.fetch({required String city}) = WeatherFetch;
}
