import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:weather/domain/weather.dart';

// required: associates our `_state.dart` with the code generated by Freezed
part 'weather_state.freezed.dart';

@freezed
class WeatherState with _$WeatherState {
  const factory WeatherState({
  required bool isLoading,
  Weather? data,
  String? error,
  }) = _WeatherState;
}

